---
# roles/open_ports/tasks/main.yml

- name: Установка UFW
  apt:
    name: ufw
    state: present
  become: yes

- name: Открытие портов
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 22
    - 80
    - 443
  become: yes

- name: Включение UFW
  ufw:
    state: enabled
  become: yes
