---
collections:
  - name: community.zabbix
    version: '>=1.5.1,<2.0.0' # Используем диапазон версий для обновлений
    # Добавляем описание
    description: Коллекция для работы с Zabbix

  - name: ansible.posix
    version: '>=1.3.0,<2.0.0'
    description: Коллекция для работы с POSIX системами

roles:
  - name: cloudalchemy.node_exporter

